<?php
/**
 * @file
 * This is the main module file.
 */

 
 
/**
* Implementation of hook_menu().
*/
function user_registration_menu() {
  $items['user_registration'] = array(
      'title' => t('Users registered for DCM 2015'),
      'description' => 'display',
      'page callback' => 'user_displaydata',      
	  'access callback' => TRUE,      
  );
    return $items;
  }
    

/**
* creating user registration form.
*/
function user_register_displayform($form) {

	$form['name']['first'] = array(
		'#type' => 'textfield',
		'#title' => t('First Name'),
		'#required' => TRUE,
		'#maxlength' => 25,
		'#size' => 25
		);
		
	$form['name']['last'] = array(
		'#type' => 'textfield',
		'#title' => t('Last Name'),
		'#required' => TRUE,
		'#maxlength' => 25,
		'#size' => 25
		);
		
	$form['number'] = array(
		'#type' => 'textfield',
		'#title' => t('Mobile Number'),
		'#required' => TRUE,
		'#maxlength' => 12,
		'#size' => 25
		);
		
	$form['address'] = array(
		 '#type' => 'textarea',
		 '#title' => t('Address'),
		 '#maxlength' => 100,
		 '#required' => TRUE,
		 );
		
	$form['age'] = array(
		'#type' => 'textfield',
		'#title' => t('Age'),
		'#required' => TRUE,
		'#maxlength' => 3,
		'#size' => 25
		);
		
	$form['country'] = array(
		'#type' => 'select',
		'#title' => t('Select Country'),
		//'#default_value' => array(2),
		'#required' => TRUE,
        '#options'=>array('USA'=>'USA','India'=>'India','China'=>'China','Nepal'=>'Nepal','Bhutan'=>'Bhutan','Bangladesh'=>'Bangladesh')
		);
		
	$form['checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => t('I agree to terms and conditions:'),
		'#required' => TRUE,
		);
		
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit')
		);
  return $form;

}



/**
* creating user registration form submit function.
*/
 function user_register_displayform_submit($form, &$form_state) {

$values = array(
  array(
    'first_name' => $form_state['values']['first'],        
    'last_name' => $form_state['values']['last'],        
    'number' => $form_state['values']['number'],        
    'address' => $form_state['values']['address'],     
     'age' => $form_state['values']['age'],  
    'country' => $form_state['values']['country'],        
  ),
  
  );
  $query = db_insert('user_registration')->fields(array('first_name','last_name','number','address','age','country'));
  foreach ($values as $record) {
   $query->values($record);
  }
  $query->execute();  
    drupal_set_message(t('Congradulations, you have successfully registered for DCM 2015'));
 }
 
 
 
 
 /**
* fetching data from the table
*/
 function user_displaydata() {
$header = array('First name', 'Last name', 'number', 'address', 'age','Country');
   $data = array();

  # set the database table
  $query = db_select('user_registration', 'p');

  # configure the query
  $query->fields('p', array('first_name', 'last_name', 'number', 'address', 'age','country'));

  # execute the query
  $results = $query->execute()->fetchAll();
  
  
   if (count($results))
   {   
		foreach ($results as $row)
		{
			$data[] = array($row->first_name, 
                  $row->last_name, 
                  $row->number, 
                  $row->address, 
                  $row->age,
				  $row->country,);
		}  
		$output = theme('table',array('header' => $header,'rows' => $data ));				
	}
	else
	{
		$output ="No records found";
	} 
    return $output;
}
 
 

  /**
* Implementation of hook_block_info().
*/  
  function user_registration_block_info() {
  $blocks = array();    
  $blocks['user_register_displayform'] = array(
    'info' => t('DCM Registration'),
     'region' => 'sidebar_second',
    'status' => TRUE,
     // 'visibility' => BLOCK_VISIBILITY_PHP,
    'pages' => '<?php global $user; if ($user->uid == 0) return TRUE; else return FALSE; ?>'
  );

  return $blocks;
}



/**
 * Implements hook_block_view().
 */
function user_registration_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  $block = array();
  switch ($delta) {
    case 'user_register_displayform':
      // Create your block content here
      $block['subject'] = t('DCM Registration');
      $block['content'] = drupal_get_form('user_register_displayform');
	  // $block['content'] = 'user_register_displayform';
      break;
  }

  return $block;
}

/**
 * Implement hook_form()
 */
function user_registration_form($node, $form_state) {
    return node_content_form($node, $form_state);
}

?>